name: p300-agent
channels:
  - conda-forge
dependencies:
  - python=3.11
  - mne>=1.7
  - numpy>=1.26
  - scipy>=1.12
  - scikit-learn>=1.4
  - matplotlib>=3.8
  - jupyterlab>=4.1
  - ipywidgets>=8.1
  - seaborn>=0.13
  - pyxdf>=1.16
  - tqdm>=4.66
  - black>=24.3
  - git-lfs
  - pip
